### ISSUE TITLE
Am I using ValueResolvers correctly

### ISSUE THREAD

**Issue by mattbrailsford** [mattbrailsford/umbraco-ditflo#1]
So in the current codebase, I make use of a lot of value resolvers to fetch values. This works pretty well, because for each resolver, you have one task, and that is to resolve the specific value. Equally, that task can be reused if needed on other models.

My only bugbear is I'm not sure if I'm just abusing the concept and some other strategy should be used, such as OnConverted handlers, or within the code of a Controller. I just really liked the granular way of working and it seemed to fit nicely.

I'm not sure what should be the correct thing to do if you need access to some external data though, such as the querystring for paging, or something like accessing an API such as getting latest tweets. 

Obviously, ValueResolvers should never be used for say, handling post backs, but you could argue what I have is correct so far, in that the job of the resolver is just to go fetch stuff.

Wadda people think?

**Comment by jamiepollock** [comment]
I think you're pretty much bang on there. Looking through the [ValueConverters](https://github.com/mattbrailsford/umbraco-ditflo/tree/master/Src/DitFlo.Web/App_Code/Ditto/ValueResolvers) in there already most of them conform to that idea.

The only one that stands out is [NewsResolver](https://github.com/mattbrailsford/umbraco-ditflo/blob/master/Src/DitFlo.Web/App_Code/Ditto/ValueResolvers/NewsResolver.cs) as that's also taking in a QueryString request object. Not entirely sure about this use case, is trying to achieve everything through Ditto the way to go? Personally I'd make a service class (love them services!) and pass in the request currentPage as a parameter to GetNews(int currentPage).

I don't think it detracts from DitFlo to show that it's flexible and can work as well as rather than instead of your standard Umbraco MVC logic. That probably adds to its strengths really.

**Comment by jamiepollock** [comment]
On the second thought, a ValueResolver is intended as a means for determining a value for a POCO property so with that in mind it doesn't specifically state what should and shouldn't be used to get that value. 

A ValueResolver is a very open concept and it is doing that one job, albeit without the decoupled nature.

**Comment by mattbrailsford** [comment]
Hey Jammie,

Thanks a tonne for taking a look at this. Really good to get a second
opinion.

I was torn by whether the news resolver should access the request myself,
but like you said, it is still technically resolving a value, its just
making a decision based on a request. This does sound like logic, but
really, I'm seeing it as view logic, rather than domain logic, so didn't
see it as a big problem.

My other thought is how would it work if it wasn't in the resolver. I guess
we'd have to construct the same value in a controller and set the value on
the model manually.

It is tricky, and I'm still not 100% so would love to hear alternate
suggestions if we have any.

**Comment by jamiepollock** [comment]
Hi Matt,
I think I'm going to have to do a fork & PR on this one to get it working. I'm not entirely sure how it'd work I'd imagine I'd need a `NewsOverviewController` (not see the node type alias) which extends the `DitFloController` and then add in something to construct it manually like you said.

I'll see what I can do at lunch!

Thanks,
Jamie

**Comment by mattbrailsford** [comment]
Cool, cheers.

Yea, I guess the controller is the right place to access the request, I'm just wondering if we can come up with a way to pass variables into the Ditto conversion so that the value resolver can still be in charge of resolving the value, but we decouple the resolver from the HTTPContext (this would likely need some changes to Ditto though).

I think going the service route would just be moving the HTTPContext dependency elsewhere unless like you say, you use a controller to access the request and pull out the variables needed.

Matt

**Comment by jamiepollock** [comment]
yea, you'd make it a parameter of the action based on the 

for example...

```C#
    public class NewsOverviewController : DitFloController {
        public ActionResult Index(RenderModel model, int currentPage = 1) {
            var viewModel = model.As<HomeViewModel>();
            var service = new NewsService();

            viewModel.News = service.GetNews(model.Content, currentPage);
            return View(viewModel);
        }
    }
```

Excuse the code if it doesn't work, I've not tried it out with DitFloController if that was a straight up RenderMvcController it should work (again no promises!).

**Comment by jamiepollock** [comment]
In addition, that code does bind to the default template I've tested it out on a vanilla v7.2.6 instance. The currentPage would match your expected querystring alias and you're providing a default if it doesn't, win win.

this passes into the service for GetNews and you have everything you need to resolve it.

**Comment by mattbrailsford** [comment]
Yea, I getcha. I guess I was pondering if we could do something like

    public class NewsOverviewController : DitFloController {
        public ActionResult Index(RenderModel model) {
            var resolverContext = new NewsValueResolverContext{
                CurrentPage = Request.QueryString["p"]
            }
            Ditto.RegisterResolverContext(resolverContext );
            return CurrentView();
        }
    }

Then the job of the controller is just to extract any vars that might be needed and register them with ditto which could autom map them to a resolver based on a constructor pattern. This way we could decouple the resolver from the httpcontext whilst still having the job of resolving the value, but the controller then is just in charge of wiring up.

Just an idea ATM

**Comment by jamiepollock** [comment]
Yep, I see what you mean, I'd still use an action parameter as that does the job of request model binding to be strongly typed but that's a minor thing.

The key here is taking the new for a request be anywhere near the ValueResolver. Also thinking more generally would this apply to external APIs like getting a Twitter feed? I wonder if there are simply some things we can't or shouldn't value resolve even if we do decouple the context?

**Comment by mattbrailsford** [comment]
I was pondering the same, but when I think about it, value resolving is basically "setting a variable", so if you moved it out of the resovler, all you do is move it to the controller. Now, I agree, the logic for how to retreive that value should likely be wrapped in a service, and shouldn't be coded in the resolver itself, but I don't think there is a problem with having the resolver request a value from a service and setting the var to the returning value. In fact, by using a resovler, you make that logic reusable and encapsulate the logic for setting such a variable in one place.

This may require us to look at possible caching strategies, but that can come once we have a good understanding of a "best practice" way of working (within the context of DitFlo)

**Comment by mattbrailsford** [comment]
PS will an action resolve query values for ChildActions too? I know in this example news is a page level view model, but it could get encapsulated into a partial with a surface controller but I'm not sure of binding action params works for these?

**Comment by mattbrailsford** [comment]
Cool, quick test and yes, you can bind action params on child only actions too :)

**Comment by jamiepollock** [comment]
Nice! Going back to your [previous comment](#issuecomment-113080492) on best practices, I think this something we should push into within the Ditto project as it's specifically to do with ValueResolvers.

**Comment by mattbrailsford** [comment]
For sure. That's one of the aims of DitFlo for me, to try and make a real world example so we can learn and feedback to Ditto.

Do you think the ResolverContexts are a good idea? Wouldn't be too hard for me to create a PR

Based upon this, and the binding stuff, my example would become:

    public class NewsOverviewController : DitFloController {
        public ActionResult Index(RenderModel model, int p) {
            Ditto.RegisterResolverContext(new NewsResolverContext{
                CurrentPage = p
            };
            return CurrentView();
        }
    }

**Comment by mattbrailsford** [comment]
Just to fill in the blank, with the above example, my value resolver might then become something like this:

    public class NewsResolver : BaseNewsResolver
    {
        private NewsResolverContext _context;

        public NewsResolver()
            : this(new NewsResolverContext())
        { }

        public NewsResolver(NewsResolverContext ctx)
        {
            _context = ctx;
        }

        public override object ResolveValue()
        {
            var currentPage = _context.CurrentPage;
            var pageSize = 2;

            var items = GetNews().ToList();
            var totalItems = items.Count;
            var totalPages = (long)Math.Ceiling(totalItems/(decimal)pageSize);

            currentPage = Math.Max(1, Math.Min(currentPage, totalPages));

            var pagedItems = items.Skip((int)(currentPage-1)*pageSize).Take(pageSize)
                .As<NewsPreviewLink>();

            return new PagedCollection<NewsPreviewLink>
            {
                CurrentPage = currentPage,
                PageSize = pageSize,
                TotalItems = totalItems,
                TotalPages = totalPages,
                Items = pagedItems
            };
        }
    }

**Comment by jamiepollock** [comment]
I see, I think I'm missing the link of how the `Ditto.RegisterResolverContext` will then apply to the NewsResolver.

Also would there be a case where you'd want multiple contexts within a single Ditto model? Say if there was a news context and a twitter context. Stop me if I'm overly complicating things.

**Comment by mattbrailsford** [comment]
Ok, so you register the context in your controller, then when the ditfloview creates the viewmodel (you aren't creating it yourself in your controller), it checks to see if the value resolver has a constructor that accepts a DittoValueResovlerContext. if it does, it gets the exact type of the context it is expecting, and looks up within a list of registered context's if one exists, if it does, it instantiates the resolver with that constructor, passing in the context. If it doesn't, then it just calls the parameterless constructor.

There shouldn't be a case where a single value resolver would need multiple contexts, however if you have multiple different values on your model, that each require their own contexts, you just register multiple contexts, ie

    public class NewsOverviewController : DitFloController {
        public ActionResult Index(RenderModel model, int p) {
            Ditto.RegisterResolverContext(new NewsResolverContext{
                CurrentPage = p
            };
            Ditto.RegisterResolverContext(new TwitterFeedResolverContext{
                SomeVar = someValue
            };
            return CurrentView();
        }
    }

In addition to this, I wouldn't generally do these globally on your hijacked pages controller, instead, I'd be creating partials, with surface controllers which setup the contexts again, so the logic is for resolving the context vars is as close to the partial as possible.

The aim of DitFlo for me is to work more granular, and get away from using giant view models, and from having page controllers resolving tones of data, in favour of having partials / surface controllers that have a more specialized job.

Any clearer?

**Comment by jamiepollock** [comment]
Yep, that makes a lot of sense.

I'm used using one ViewModel with inheritance, eg...

BasicPageViewModel
 - HomePageViewModel
 - NewsPageViewModel
 - ContentPageViewModel

Where BasicPageViewModel would have the header and footer on them. Still a lot to get my head around as this is a new way of working. I'm also a big fan of using the DisplayFor and getting strongly typed models into convention over configuration DisplayTemplates & EditorTemplates rather than Partial. Mostly because of how well they deal with an abstract type and find the concrete class version for me. A lot of what we've done recently has been about re-utilising a single space with different similar components (eg. a Video, Audio or Gallery component).

**Comment by mattbrailsford** [comment]
Yea, I just find that setup hard to manage myself, and you end up with dupilcation / hidden properties nested on base classes. With this idea, you have lots of small models with one purpose so it's much easier to discover what does what and then DitFlo handles generating the smaller view models on demand. It's a very different concept indeed, but I'm hoping it's got legs.

I'm going to continue the discussion of ValueResolverContexts on the Ditto issue tracker here https://github.com/leekelleher/umbraco-ditto/issues/94 as like you say, that's a Ditto thing, but happy to keep talking concepts here.

**Comment by mattbrailsford** [comment]
PS You should still be able to use DisplayFor etc. I don't see DitFlo stopping you from doing this, all it really does is break your big view model into smaller ones. You can still use data attributes on your models and use all the existing razor helpers to render the values.

**Comment by mattbrailsford** [comment]
...and if you can't, that's a bug, so let me know :)

**Comment by jamiepollock** [comment]
Another thing to get my head around is, I'm also used to using standard MVC vocab when it comes to Umbraco MVC. So using `View(viewModel)` rather than `CurrentTemplate(viewModel)` and a `@model My.ViewModels.X`. The latter wouldn't work due to the requirement of `@implements DitFloView<T>`.

I like what's going on here though. Perhaps I should share how I do Ditto? I like what's going on here with DitFlo, it takes a lot of the repetition out eg wiring up controllers etc. Maybe working in a granular way would be the way to go in the future.

**Comment by mattbrailsford** [comment]
I'd love to see how you use Ditto.

I know what you mean about the subtle differences between MVC and Umbraco MVC.

RE DitFloView though, right now, I do need to keep it just because that is what allows you to have different viewmodels per partial / template. Without it, MVC forces you to have a common model throughout (unless you specifically pass through a model when calling Html.Partial("", model), but it's this kind of chaining I hate).

**Comment by jamiepollock** [comment]
Well it does the job you need it to, instead of wiring up an expected viewmodel to a view via the controller you're doing it via the implements declaration. I shouldn't think that should change, that's what makes DitFlo so reusable and avoid additional controllers plus makes it lightweight when making partials too instead of a big viewmodel.

**Comment by mattbrailsford** [comment]
Hey @jamiepollock checkout the latest code to see news using a ValueResolerContext to decouple it from the HttpContext :)

Wadda you think?

**Comment by jamiepollock** [comment]
Hey Matt, just had a look through. Definitely looks like a more logical approach!

Bugbear: is there no way to provide a default value to a long as a method parameter? Weird! :)

**Comment by mattbrailsford** [comment]
I think it's more the fact you need to be able to handle a URL with no p param at all aswell so you have to make it nullable, otherwise you'd have to create 2 actions, one with a param, one without.

**Comment by jamiepollock** [comment]
I've tested `public ActionResult Index(RenderModel model, long p = 1)` and it work fine with a default value. So no need for two actions. Routing will use the default value specified is no querystring or form value called p is present. :)

**Comment by mattbrailsford** [comment]
Ahhh, even better! Updating now :)

**Comment by jamiepollock** [comment]
Cool, so you reckon ValueResolverContexts will be useful for getting external data sources? Expecting the next issue to be "Am I using ValueResolverContexts correctly"?

**Comment by mattbrailsford** [comment]
:)

Resovler contexts are that, they allow you to feed contextual information into your resolver, so maybe you keep an APIKey in your app settings, or you need to access a cookie or something, then these give you a method of passing values in needed by your resolver in order to resolve it's value. You shouldn't be passing in big collections, the resolver should lookup the values itself (ie, connect to the api), but it's fine for it to pass in config settings.

**Comment by jamiepollock** [comment]
Gotcha!
