### ISSUE TITLE
What's in a name?

### ISSUE THREAD

**Issue by leekelleher** [mattbrailsford/umbraco-ditflo#5]
Are you happy with the name? Has it stuck yet, or are you looking for alternatives?

The reason I ask, (I know we've chatted about this before), is that after cloning/pulling the repo, seeing "umbraco-ditto" and "umbraco-ditflo" folders next to each other, I kept getting confused between the projects. :confused:

No biggie, only a thought.

**Comment by mattbrailsford** [comment]
I'm not averse to changing it, though I do quite like it. Its clearly ditto
related and short which are my main things.

I guess we could change it to Ditto Framework or something and just have
DittoView, DittoController etc

Thoughts?

**Comment by leekelleher** [comment]
I know I'd suggested calling it "Ditto Framework" during CG15, but in hindsight, I think it would lead to confusion between the projects.

Currently, the only suggestion I have is another Pokemon related one... Ditto's owner is called Duplica. ;-)

**Comment by mattbrailsford** [comment]
Hmmm, I'll have to have a think then. Right now I'm tempted to keep it as
DitFlo if we want to keep it non-ditto affiliated. (Not a fan of Duplica)

**Comment by leekelleher** [comment]
Keep it as DitFlo.

The Duplica thing was just something I stumbled on whilst searching.

**Comment by mattbrailsford** [comment]
We'll stick with DitFlo then
